### ISSUE TITLE
Touchscreen (mouse) cursor is broken in 4.1

### ISSUE THREAD

**Issue by dderby** [pali/linux-n900#1]
The TSC2005 touchscreen is unusable when using kernel built from either of your 4.1 branches (both rc2 and rc4).  Attempting to move the mouse cursor under X11 results in the cursor getting stuck in the corner of the screen.

This is a regression as it works fine with a kernel built from your v4.0-rc1-n900 branch.

**Comment by pali** [comment]
This problem should be fixed in upstream torvalds repository:
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=8770d0898af7f0f0a8e88ce702b02a9ca326254f

In future, please report such problems directly to maintainers of (non-working) driver or to specific mailing list. See MAINTAINERS file or use script scripts/get_maintainer.pl

**Comment by dderby** [comment]
Thanks Pali.  I'll keep that in mind in future.
